CREATE TABLE IF NOT EXISTS email_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    template_name VARCHAR(255) NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_email_template_tenant_name
    ON email_template (tenant_id, template_name);

CREATE TABLE IF NOT EXISTS tenant_configuration (
    tenant_id VARCHAR(255) PRIMARY KEY,
    email_host VARCHAR(100),
    email_rate_limit INT,
    retry_count INT,
    retry_interval INT
);

